apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-front-end
  name: udagram-front-end-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udagram-front-end
    