apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-api-feed
  name: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
        service: udagram-api-feed
    spec:
      containers:
      - image: markmavromatis/udagram-api-feed
        name: udagram-api-feed
        imagePullPolicy: Always          
        env:
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: POSTGRES_PASSWORD
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: web-user-authentication
                key: jwt-secret
          - name: POSTGRES_DB
            value: udagram_mavromatis_dev
          - name: POSTGRES_HOST
            value: udagram-mavromatis-dev.cguzw4eojx3a.us-east-2.rds.amazonaws.com
          - name: AWS_REGION
            value: us-east-2
          - name: AWS_PROFILE
            value: default
          - name: AWS_BUCKET
            value: udagram-mavromatis-dev
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: aws-secret
            mountPath: "/root/.aws/"
            readOnly: true
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
